spring:
  #database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/comp7506
    username: root
    password: 7506data

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl